// react-app/src/pages/Day2/components/cart-list-item/index.tsx
import { Button } from 'antd';

import { ReactComponent as ChevronLeft } from '../../images/chevron-left.svg';
import { ReactComponent as ChevronRight } from '../../images/chevron-right.svg';
import { CartItem } from '../../models';
import styles from './styles.module.scss';

const CartListItem = ({ item, onIncrease, onDecrease }: Props): JSX.Element => {
  return (
    <div className={styles.item}>
      <img className={styles.item__img} src={item.image} />
      <div>
        <div className={styles.item__name}>
          {item.name}
        </div>
        <div className={styles.item__price}>
          ${item.price}
        </div>
        <div className="flex items-center justify-between">
          <div className="flex items-center justify-between w-32">
            <Button
              className={styles.item_btnAdjust}
              type="primary"
              shape="circle"
              icon={<ChevronLeft />}
              onClick={(): void => onDecrease(item)}
            />
            <span>{item.quantity}</span>
            <Button
              className={styles.item_btnAdjust}
              type="primary"
              shape="circle"
              icon={<ChevronRight />}
              onClick={(): void => onIncrease(item)}
            />
          </div>
          <span className={styles.item__totalPrice}>
            ${item.price * item.quantity}
          </span>
        </div>
      </div>
    </div>
  );
};

type Props = {
  item: CartItem;
  onIncrease: (item: CartItem) => void;
  onDecrease: (item: CartItem) => void;
}

export { CartListItem };

// angular/src/app/day-2/components/cart-list-item/cart-list-item.component.ts
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CartItem } from '../../models';

@Component({
  selector: 'app-cart-list-item',
  templateUrl: './cart-list-item.component.html',
  styleUrls: ['./cart-list-item.component.scss'],
})
export class CartListItemComponent {
  @Input()
  public item: CartItem | undefined;

  @Output()
  public onIncrease = new EventEmitter<void>();

  @Output()
  public onDecrease = new EventEmitter<void>();
}

<div class="item" *ngIf="item">
  <img class="item__img" [attr.src]="item.image" />
  <div>
    <div class="item__name">
      {{ item.name }}
    </div>
    <div class="item__price">
      ${{ item.price }}
    </div>
    <div class="flex items-center justify-between">
      <div class="flex items-center justify-between w-32">
        <button
          class="item_btn-adjust"
          nz-button
          nzType="primary"
          (click)="onDecrease.emit()"
        >
          <img src="/assets/images/day-2/chevron-left.svg">
        </button>
        <span>{{ item.quantity }}</span>
        <button
          class="item_btn-adjust"
          nz-button
          nzType="primary"
          (click)="onIncrease.emit()"
        >
          <img src="/assets/images/day-2/chevron-right.svg">
        </button>
      </div>
      <span class="item__total-price">
        ${{ item.price * item.quantity }}
      </span>
    </div>
  </div>
</div>
