// vue/src/pages/day-2/shared/components/DishListItem.vue
<script setup lang="ts">
import type { PropType } from 'vue';
import type { Dish } from '../models';

defineProps({
  item: Object as PropType<Dish>,
});

const emits = defineEmits<{
  (e: 'onAddToCart', item: Dish): void;
}>();
</script>

<template>
  <div class="dish">
    <div class="dish__inner" :style="{ background: item?.bgColor }">
      <img class="dish__img" :src="item?.image" />

      <div class="relative pt-6">
        <div class="dish__name">
          {{ item?.name }}
        </div>
        <div class="dish__price">${{ item?.price }}</div>
        <a-button
          class="dish__btn-add"
          type="primary"
          shape="round"
          @click="emits('onAddToCart', item as Dish)"
        >
          Add to Cart
        </a-button>
      </div>
    </div>
  </div>
</template>

<style scoped lang="scss">
.dish {
  min-height: 145px;

  &__inner {
    display: flex;
    margin: 32px 0 0 26px;
    border-radius: 20px 0 0 20px;
  }

  &__img {
    width: 144px;
    height: auto;
    transform: translate(-16px, -16px);
  }

  &__name {
    width: 80%;
    margin-bottom: 15px;
    font-size: 18px;
    line-height: 20px;
  }

  &__price {
    font-size: 28px;
    line-height: 28px;
    font-weight: bold;
  }

  &__btn-add {
    position: absolute;
    bottom: -12px;
    width: 130px;
    border: 0;
    font-size: 16px;
    font-weight: bold;
    background-color: var(--color-theme);
  }
}
</style>

// react-app/src/pages/Day2/components/dish-list-item/index.tsx
import { Button } from 'antd';

import { Dish } from '../../models';
import styles from './styles.module.scss';

const DishListItem = ({ item, onAddToCart }: Props): JSX.Element => {
  return (
    <div className={styles.dish}>
      <div className={styles.dish__inner} style={{ background: item.bgColor }}>
        <img className={styles.dish__img} src={item.image} />
        <div className="relative pt-6">
          <div className={styles.dish__name}>
            {item.name}
          </div>
          <div className={styles.dish__price}>
            ${item.price}
          </div>
          <Button className={styles['dish__btn-add']} type="primary" shape="round" size="middle" onClick={(): void => onAddToCart(item)}>
            Add to Cart
          </Button>
        </div>
      </div>
    </div>
  );
};

type Props = {
  item: Dish;
  onAddToCart: (item: Dish) => void,
}

export { DishListItem };
