// angular/src/app/day-4/day-4.component.ts
import { CommonModule } from '@angular/common';
import { ChangeDetectionStrategy, Component, OnDestroy, OnInit, QueryList, TrackByFunction, ViewChildren } from '@angular/core';

import { KeyComponent } from './key/key.component';
import { Rows } from './models/constant';
import { Key } from './models/model';

@Component({
  standalone: true,
  selector: 'app-day-4',
  templateUrl: './day-4.component.html',
  styleUrls: ['./day-4.component.scss'],
  imports: [CommonModule, KeyComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Day4Component implements OnInit, OnDestroy {
  @ViewChildren(KeyComponent)
  public keys!: QueryList<KeyComponent>;

  public readonly Rows = Rows;

  public ngOnInit(): void {
    document.addEventListener('keydown', this.handleKeydown.bind(this));
  }

  public ngOnDestroy(): void {
    document.removeEventListener('keydown', this.handleKeydown.bind(this));
  }

  private handleKeydown(e: KeyboardEvent): void {
    const keyEl = this.keys.find(k => k.key.code === e.code);
    keyEl?.jiggle();
  }

  public trackByIndex: TrackByFunction<number> = (_, i: number): number => i;

  public trackByKeyCode: TrackByFunction<Key> = (_, key: Key): Key['code'] => key.code;
}

<div class="wrapper">
  <div
    class="row"
    [class]="'row--' + (i + 1)"
    *ngFor="let row of Rows; let i = index; trackBy: trackByIndex"
  >
    <app-key *ngFor="let key of row; trackBy: trackByKeyCode" [key]="key">
    </app-key>
  </div>
</div>

// react-app/src/pages/Day4/index.tsx
import React, { useRef, ReactElement, useEffect } from 'react';

import { Rows } from './models/constant';
import styles from './styles.module.scss';
import Key, { KeyMethods } from './components/key';

const Day4 = (): ReactElement => {
  const keyRefs = useRef<(KeyMethods | null)[]>([]);

  useEffect(() => {
    document.addEventListener('keydown', handleKeydown);

    return function cleanup(): void {
      document.removeEventListener('keydown', handleKeydown);
    };
  }, []);

  const handleKeydown = (e: KeyboardEvent): void => {
    const keyEl = keyRefs.current.find(k => k?.getCode() === e.code);
    keyEl?.jiggle();
  };

  return (
    <div className={styles.wrapper}>
      {Rows.map((row, index) => (
        <div className={styles.row + ' ' + styles[`row--${index + 1}`]} key={index}>
          {row.map(key => (
            <Key
              ref={(el): KeyMethods | null => {
                keyRefs.current.push(el);
                return el;
              }}
              key={key.code}
              data={key}
            />
          ))}
        </div>
      ))}
    </div>
  );
};

export default Day4;
