// react-app/src/pages/Day2/components/cart/index.tsx
import { CartItem } from '../../models';
import { useCartContext } from '../../providers/cart.hook';
import { CartListItem } from '../cart-list-item';
import styles from './styles.module.scss';

const Cart = (): JSX.Element => {
  const { cart, addItem, decreaseItemQty } = useCartContext();

  const handleAddItem = (item: CartItem): void => {
    addItem(item);
  };

  const handleDecreaseQty = (item: CartItem): void => {
    decreaseItemQty(item.id);
  };

  return (
    <div className="mx-8 mb-10">
      {cart.items.length === 0 && <p>Your cart is empty.</p>}
      {cart.items.length > 0 &&
        <>
          {cart.items.map(item =>
            <CartListItem
              item={item}
              key={item.id}
              onIncrease={handleAddItem}
              onDecrease={handleDecreaseQty}
            />
          )}
          <div className={styles.totalSection}>
            <span className={styles.totalSection__label}>Subtotal:</span>
            <span className={styles.totalSection__price}>${cart.subtotal.toFixed(2)}</span>
            <span className={styles.totalSection__label}>Tax:</span>
            <span className={styles.totalSection__price}>${cart.tax.toFixed(2)}</span>
            <span className={styles.totalSection__label}>Total:</span>
            <span className={`${styles.totalSection__price} ${styles.totalSection__totalPrice}`}>${cart.total.toFixed(2)}</span>
          </div>
        </>
      }
    </div>
  );
};

export { Cart };

// angular/src/app/day-2/components/cart/cart.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';
import { CartItem } from '../../models';

import { CartService } from '../../services/cart.service';

@Component({
  selector: 'app-cart',
  templateUrl: './cart.component.html',
  styleUrls: ['./cart.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class CartComponent {

  public cart$ = this.cartService.cart$;

  constructor(private cartService: CartService) { }

  public handleAddItem(item: CartItem): void {
    this.cartService.addItem(item);
  };

  public handleDecreaseQty(item: CartItem): void {
    this.cartService.decreaseItemQty(item.id);
  };

  public trackByFn(_: number, item: CartItem): string {
    return item.id;
  }
}

<div class="mx-8 mb-10" *ngIf="cart$ | async as cart">
  <p *ngIf="cart.items.length === 0">Your cart is empty.</p>

  <ng-container *ngIf="cart.items.length > 0">
    <div>
      <div class="cart-item" *ngFor="let item of cart.items; trackBy: trackByFn">
        <app-cart-list-item
          [item]="item"
          (onIncrease)="handleAddItem(item)"
          (onDecrease)="handleDecreaseQty(item)"
        ></app-cart-list-item>
      </div>
    </div>
    <div class="total-section">
      <span class="total-section__label">Subtotal:</span>
      <span class="total-section__price">${{ cart.subtotal.toFixed(2) }}</span>
      <span class="total-section__label">Tax:</span>
      <span class="total-section__price">${{ cart.tax.toFixed(2) }}</span>
      <span class="total-section__label">Total:</span>
      <span class="total-section__price total-section__total-price">${{ cart.total.toFixed(2) }}</span>
    </div>
  </ng-container>
</div>
