// angular/src/app/day-1/day-1.component.ts
import { ChangeDetectionStrategy, ChangeDetectorRef, Component } from '@angular/core';
import { NzModalService } from 'ng-zorro-antd/modal';
import { ISettings, SettingsModalComponent } from './settings-modal/settings-modal.component';

const MAX_SECONDS = 3599; // 59:59 (m:s)

@Component({
  selector: 'app-day-1',
  templateUrl: './day-1.component.html',
  styleUrls: ['./day-1.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Day1Component {
  public visible = false;
  public duration = 0;
  public animating = false;
  public ringColor = '#900a0a';

  private minute = 0;
  private second = 0;
  private totalInSeconds = 0;
  private timer: any;

  constructor(
    private modalService: NzModalService,
    private cdr: ChangeDetectorRef,
  ) {}

  public get minuteString(): string {
    return `${this.minute}`.padStart(2, '0');
  }

  public get secondString(): string {
    return `${this.second}`.padStart(2, '0');
  }

  public toggleTimer(): void {
    if (!this.animating && this.totalInSeconds > 0) {
      this.animating = true;
      this.ringColor = '#900a0a';
      this.timer = setInterval(() => {
        this.totalInSeconds > 1 ? (this.totalInSeconds -= 1) : this.finish();
        this.refreshNumbers();
      }, 1000);
    } else {
      this.reset();
    }
  }

  private reset(): void {
    clearInterval(this.timer);
    this.totalInSeconds = 0;
    this.duration = 0;
    this.minute = 0;
    this.second = 0;
    this.animating = false;
  }

  private finish(): void {
    this.reset();
    this.ringColor = 'green';
    this.modalService.info({ nzTitle: "Time's up" });
  }

  private refreshNumbers(): void {
    const timeValue = new Date(this.totalInSeconds * 1000)
      .toISOString()
      .substr(14, 5);
    const [m, s] = timeValue.split(':');

    this.minute = +m;
    this.second = +s;
    this.cdr.markForCheck();
  }

  public openSettingModal(): void {
    const modal = this.modalService.create({
      nzTitle: 'Settings',
      nzContent: SettingsModalComponent,
      nzFooter: null,
      nzWidth: 350,
    });

    modal.afterClose.subscribe((result: ISettings) => {
      const { minutes = 0, seconds = 0 } = result;
      this.totalInSeconds = Math.min(MAX_SECONDS, minutes * 60 + seconds);
      this.duration = this.totalInSeconds;
      this.refreshNumbers();
    });
  }
}

<div class="wrapper">
  <div class="circle">
    <span class="time">
      <span class="time__minute">{{ minuteString }}</span
      >:<span class="time__second">{{ secondString }}</span>
    </span>
    <a class="btn-start" (click)="toggleTimer()">
      {{ animating ? 'Stop' : 'Start' }}
    </a>
    <a class="btn-setting" (click)="openSettingModal()">
      <img class="btn-setting__icon mx-auto" src="/assets/icons/gear.svg" />
    </a>
  </div>
  <svg class="ring-svg" height="520" width="520">
    <circle
      [style.--duration.s]="duration"
      [style.--ring-color]="ringColor"
      [class.animate]="animating"
      class="ring"
      cx="260"
      cy="260"
      r="255"
    ></circle>
  </svg>

  <svg
    class="drop-svg"
    width="622"
    height="637"
    viewBox="0 0 622 637"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g filter="url(#filter0_dd_108_2)">
      <circle cx="308" cy="320" r="259" fill="black" />
    </g>
    <defs>
      <filter
        id="filter0_dd_108_2"
        x="0"
        y="-5"
        width="622"
        height="642"
        filterUnits="userSpaceOnUse"
        color-interpolation-filters="sRGB"
      >
        <feFlood flood-opacity="0" result="BackgroundImageFix" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="5" dy="-16" />
        <feGaussianBlur stdDeviation="25" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0.15 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_108_2"
        />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dx="-5" dy="14" />
        <feGaussianBlur stdDeviation="22" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0"
        />
        <feBlend
          mode="normal"
          in2="effect1_dropShadow_108_2"
          result="effect2_dropShadow_108_2"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect2_dropShadow_108_2"
          result="shape"
        />
      </filter>
    </defs>
  </svg>
</div>

// react-app/src/pages/Day1/index.tsx
import { CSSProperties, ReactElement, useEffect, useRef, useState } from 'react';
import { FormInstance, InputNumber, Modal, Form } from 'antd';

import { ReactComponent as DropSVG } from './drop-svg.svg';
import { ReactComponent as GearIcon } from 'src/assets/icons/gear.svg';

import styles from './styles.module.scss';

const Day1 = (): ReactElement => {
  const MAX_SECONDS = 3599; // 59:59 (m:s)
  const formRef = useRef<FormInstance>(null);
  const [ringColor, setRingColor] = useState('#900a0a');
  const [timer, setTimer] = useState<NodeJS.Timeout>();
  const [totalInSeconds, setTotalInSeconds] = useState(0);
  const [minute, setMinute] = useState(0);
  const [duration, setDuration] = useState(0);
  const [second, setSecond] = useState(0);
  const [isModalVisible, setModalVisible] = useState(false);
  const [animating, setAnimating] = useState(false);

  useEffect(() => {
    if (totalInSeconds >= 1) {
      refreshNumbers();
    } else if (animating) {
      finish();
      clearInterval(timer as NodeJS.Timeout);
    }
  }, [totalInSeconds, animating]);

  const handleSubmitSetting = (): void => {
    const { minutes = 0, seconds = 0 } = formRef.current?.getFieldsValue();
    const duration = minutes * 60 + seconds;
    setTotalInSeconds(Math.min(MAX_SECONDS, duration));
    setDuration(duration);
    hideModal();
  };

  const toggleTimer = (): void => {
    if (!animating && totalInSeconds > 0) {
      setAnimating(true);
      setRingColor('#900a0a');

      const t = setInterval(() => {
        setTotalInSeconds(prev => prev - 1);
      }, 1000);
      setTimer(t);
    } else {
      reset();
    }
  };

  const reset = (): void => {
    setTotalInSeconds(0);
    setDuration(0);
    setMinute(0);
    setSecond(0);
    setAnimating(false);
  };

  const finish = (): void => {
    reset();
    setRingColor('green');
    Modal.info({ title: 'Time\'s up' });
  };

  const refreshNumbers = (): void => {
    const timeValue = new Date(totalInSeconds * 1000)
      .toISOString()
      .substr(14, 5);
    const [m, s] = timeValue.split(':');

    setMinute(+m);
    setSecond(+s);
  };

  const hideModal = (): void => {
    setModalVisible(false);
  };

  const showModal = (): void => {
    setModalVisible(true);
  };

  return (
    <div className={styles.wrapper}>
      <div className={styles.circle}>
        <span className={styles.time}>
          <span className={styles.time__minute}>{`${minute}`.padStart(2, '0')}</span>:
          <span className={styles.time__second}>{`${second}`.padStart(2, '0')}</span>
        </span>
        <a className={styles['btn-start']} onClick={toggleTimer}>
          {animating ? 'Stop' : 'Start'}
        </a>
        <a className={styles['btn-setting']} onClick={showModal}>
          <GearIcon className={styles['btn-setting__icon']} />
          {/* <img  src="assets/icons/gear.svg" /> */}
        </a>
      </div>
      <svg className={styles['ring-svg']} height="520" width="520">
        <circle
          style={{ '--duration': `${duration}s`, '--ring-color': ringColor } as CSSProperties}
          className={`${styles.ring} ${animating ? styles.animate : ''}`}
          cx="260"
          cy="260"
          r="255"
        ></circle>
      </svg>

      <DropSVG className={styles['drop-svg']} />

      <Modal title="Settings" visible={isModalVisible} onOk={handleSubmitSetting} onCancel={hideModal}>
        <Form
          name="settings"
          autoComplete="off"
          ref={formRef}
        >
          <Form.Item
            label="Minutes"
            name="minutes"
          >
            <InputNumber />
          </Form.Item>
          <Form.Item
            label="Seconds"
            name="seconds"
          >
            <InputNumber />
          </Form.Item>
        </Form>
      </Modal>
    </div>
  );
};

export default Day1;
