// react-app/src/pages/Day2/components/dish-list-item/index.tsx
import { Button } from 'antd';

import { Dish } from '../../models';
import styles from './styles.module.scss';

const DishListItem = ({ item, onAddToCart }: Props): JSX.Element => {
  return (
    <div className={styles.dish}>
      <div className={styles.dish__inner} style={{ background: item.bgColor }}>
        <img className={styles.dish__img} src={item.image} />
        <div className="relative pt-6">
          <div className={styles.dish__name}>
            {item.name}
          </div>
          <div className={styles.dish__price}>
            ${item.price}
          </div>
          <Button className={styles['dish__btn-add']} type="primary" shape="round" size="middle" onClick={(): void => onAddToCart(item)}>
            Add to Cart
          </Button>
        </div>
      </div>
    </div>
  );
};

type Props = {
  item: Dish;
  onAddToCart: (item: Dish) => void,
}

export { DishListItem };

// angular/src/app/day-2/components/dish-list-item/dish-list-item.component.ts
import { Component, ChangeDetectionStrategy, Output, EventEmitter, Input } from '@angular/core';

import { Dish } from '../../models';

@Component({
  selector: 'app-dish-list-item',
  templateUrl: './dish-list-item.component.html',
  styleUrls: ['./dish-list-item.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class DishListItemComponent {
  @Input()
  public item: Dish = {} as Dish;

  @Output()
  public onAddToCart = new EventEmitter<Dish>();
}

<div class="dish">
  <div class="dish__inner" [style.background]="item.bgColor">
    <img class="dish__img" [attr.src]="item.image" />
    <div class="relative pt-6">
      <div class="dish__name">
        {{ item.name }}
      </div>
      <div class="dish__price">
        ${{ item.price }}
      </div>
      <button
        class="dish__btn-add"
        nz-button
        nzType="primary"
        nzShape="round"
        (click)="onAddToCart.emit(item)"
      >
        Add to Cart
      </button>
    </div>
  </div>
</div>
