// react-app/src/pages/Day2/index.tsx
import { ReactElement } from 'react';

import { ReactComponent as BGLeft } from './images/bg__left.svg';
import { ReactComponent as BGTopRight } from './images/bg__top-right.svg';
import { ReactComponent as BGBottomRight } from './images/bg__btm-right.svg';
import { Card } from './components/card';
import { DishList } from './components/dish-list';
import { dishes } from './models';
import styles from './styles.module.scss';

const Day2 = (): ReactElement => {
  return (
    <div className={styles.wrapper + ' relative flex justify-center items-start gap-14'}>
      <BGLeft className={styles['bg-left'] + ' absolute left-0'} />
      <BGTopRight className="absolute top-0 right-0" />
      <BGBottomRight className={styles['bg-bottom-right'] + ' absolute bottom-0 right-0'} />

      <Card className={styles.card} title="To Go Menu">
        <DishList items={dishes} />
      </Card>

      <Card className={styles.card} title="Your Cart">

      </Card>
    </div>
  );
};

export default Day2;

// angular/src/app/day-2/day-2.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

import { dishes } from './models';

@Component({
  selector: 'app-day-2',
  templateUrl: './day-2.component.html',
  styleUrls: ['./day-2.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class Day2Component {
  public dishes = dishes;
}

<div class="wrapper relative flex justify-center items-start gap-14">
  <img class="bg-left absolute left-0" src="/assets/images/day-2/bg__left.svg">
  <img class="absolute top-0 right-0" src="/assets/images/day-2/bg__top-right.svg">
  <img class="bg-bottom-right absolute bottom-0 right-0" src="/assets/images/day-2/bg__btm-right.svg">

  <app-card title="To Go Menu">
    <app-dish-list [items]="dishes"></app-dish-list>
  </app-card>

  <app-card title="Your Cart">
    <app-cart></app-cart>
  </app-card>
</div>
