// react-app/src/pages/Day2/components/dish-list/index.tsx
import { DishListItem } from '..';
import { Dish } from '../../models';
import { useCartContext } from '../../providers/cart.hook';

const DishList = ({ items }: Props): JSX.Element => {
  const { addItem } = useCartContext();

  const handleAddItemToCart = (item: Dish): void => {
    addItem(item);
  };

  return (
    <div className="mb-8">
      {items.map(dish => (
        <DishListItem item={dish} key={dish.id} onAddToCart={handleAddItemToCart} />
      ))}
    </div>
  );
};

type Props = {
  items: Array<Dish>;
}

export { DishList };

// vue/src/pages/day-2/shared/components/DishList.vue
<script setup lang="ts">
import type { Dish } from '../models';
import DistListItem from './DishListItem.vue';
import { useCartStore } from '../stores/cart';

defineProps({
  items: Array<Dish>,
});

const { addItem } = useCartStore();
</script>

<template>
  <div class="mb-8">
    <DistListItem
      v-for="dish in items"
      :key="dish.id"
      :item="dish"
      @onAddToCart="addItem($event)"
    ></DistListItem>
  </div>
</template>
