// angular/src/app/day-2/components/dish-list/dish-list.component.ts
import { Component, ChangeDetectionStrategy, Input } from '@angular/core';

import { Dish } from '../../models';
import { CartService } from '../../services/cart.service';

@Component({
  selector: 'app-dish-list',
  templateUrl: './dish-list.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class DishListComponent {

  @Input()
  public items: Array<Dish> = [];

  constructor(private cartService: CartService) { }

  public handleAddItemToCart(item: Dish): void {
    this.cartService.addItem(item);
  };
}

<div class="mb-8">
  <app-dish-list-item *ngFor="let dish of items"
    [item]="dish"
    (onAddToCart)="handleAddItemToCart($event)"
  ></app-dish-list-item>
</div>

// vue/src/pages/day-2/shared/components/DishList.vue
<script setup lang="ts">
import type { Dish } from '../models';
import DistListItem from './DishListItem.vue';
import { useCartStore } from '../stores/cart';

defineProps({
  items: Array<Dish>,
});

const { addItem } = useCartStore();
</script>

<template>
  <div class="mb-8">
    <DistListItem
      v-for="dish in items"
      :key="dish.id"
      :item="dish"
      @onAddToCart="addItem($event)"
    ></DistListItem>
  </div>
</template>
