// react-app/src/pages/Day3/components/audio/index.tsx
import { forwardRef, ForwardRefRenderFunction, useImperativeHandle, useRef } from 'react';

export type AudioMethods = {
  play: () => void;
}

const Audio: ForwardRefRenderFunction<AudioMethods, LayoutProps> = (props, ref) => {
  const audioRef = useRef<HTMLAudioElement>(null);

  useImperativeHandle(ref, (): AudioMethods => ({
    play: (): void => {
      if (!audioRef.current) {
        return;
      }

      const player = audioRef.current;

      if (!player.paused) {
        player.pause();
        player.currentTime = 0;
      }

      player.play();
    },
  }));

  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const mediaFile = require(`../../medias/${props.file}`);

  return (
    <audio ref={audioRef}>
      <source src={mediaFile} type="audio/mpeg" />
    </audio>
  );
};

interface LayoutProps {
  file: string;
}

export default forwardRef(Audio);

// angular/src/app/day-3/audio/audio.component.ts
import { ChangeDetectionStrategy, Component, ElementRef, Input, ViewChild } from '@angular/core';

@Component({
  standalone: true,
  selector: 'app-audio',
  templateUrl: './audio.component.html',
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class AudioComponent {
  @Input()
  public file!: string;

  @ViewChild('audio')
  public audioRef!: ElementRef<HTMLAudioElement>;

  private get audioPlayer(): HTMLAudioElement {
    return this.audioRef.nativeElement;
  }

  public play(): void {
    if (!this.audioPlayer) {
      return;
    }

    if (!this.audioPlayer.paused) {
      this.audioPlayer.pause();
      this.audioPlayer.currentTime = 0;
    }

    this.audioPlayer.play();
  }
}

<audio #audio>
  <source [attr.src]="'/assets/medias/day-3/' + file" type="audio/mpeg" />
</audio>
