// react-app/src/pages/Day4/components/key/index.tsx
import { forwardRef, ForwardRefRenderFunction, useImperativeHandle, useRef } from 'react';

import { Key as KeyModel } from '../../models/model';
import styles from './styles.module.scss';

export type KeyMethods = {
  jiggle: () => void;
  getCode: () => KeyModel['code'];
}

const Key: ForwardRefRenderFunction<KeyMethods, Props> = (props, ref) => {
  const keyRef = useRef<HTMLElement>(null);

  const jiggle = (): void => {
    if (!keyRef.current) {
      return;
    }

    const keyEl = keyRef.current;

    keyEl.classList.add(styles.jiggling);

    setTimeout(() => {
      keyEl.classList.remove(styles.jiggling);
    }, 500);
  };

  const getCode = (): KeyModel['code'] => props.data.code;

  useImperativeHandle(ref, (): KeyMethods => ({
    jiggle,
    getCode,
  }));

  return (
    <span className={styles.key} ref={keyRef}  style={{ color: props.data?.color }} onClick={jiggle}>
      { props.data?.char }
    </span>
  );
};

interface Props {
  data: KeyModel,
}

export default forwardRef(Key);

// angular/src/app/day-4/key/key.component.ts
import { ChangeDetectionStrategy, Component, ElementRef, Input, ViewChild } from '@angular/core';
import { Key } from '../models/model';

@Component({
  standalone: true,
  selector: 'app-key',
  templateUrl: './key.component.html',
  styleUrls: ['./key.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class KeyComponent {
  @Input()
  public key!: Key;

  @ViewChild('keyRef')
  public keyRef!: ElementRef<HTMLElement>;

  private get audioPlayer(): HTMLElement {
    return this.keyRef.nativeElement;
  }

  public jiggle(): void {
    if (!this.audioPlayer) {
      return;
    }

    this.audioPlayer.classList.add('jiggling');

    setTimeout(() => {
      this.audioPlayer.classList.remove('jiggling');
    }, 500);
  }
}

<span class="key" #keyRef [style]="{ color: key.color }" (click)="jiggle()">
  {{ key.char }}
</span>
